// main.cpp -- correctness check for the ISPC sin(x) kernel.
//
// Runs the interleaved ISPC variant (ispc_sinx, from sinx_interleaved.ispc) over a
// handful of sample values and prints its output next to std::sin so the Taylor-series
// approximation can be eyeballed against the real thing. This is a sanity check, not a
// benchmark -- see bench.cpp for timing and for comparing the interleaved, blocked, and
// foreach variants against each other.
//
// Expect the two columns to agree closely near x = 0 and to drift apart as x grows:
// the kernel is a Maclaurin series (expanded about 0), so accuracy falls off with
// distance from the origin. At x = 3.14 with terms = 5 the error is ~4e-4.
//
// N = 8 matches programCount for the avx2-i32x8 target, so the whole array is one
// full gang -- every lane is active and no bounds check is exercised.
//
// terms must stay <= 5: denom in the .ispc kernel is a uniform int holding (2j+1)!,
// which overflows int32 once j reaches 6 (13! = 6.2e9).
//
// Declarations come from sinx_interleaved.h, generated by ispc's -h flag; ispc puts
// them in namespace ispc, hence the qualified call below.
//
// Build:
//   ispc -O2 --arch=x86-64 --target=avx2-i32x8 -h sinx_interleaved.h -o sinx_interleaved.obj sinx_interleaved.ispc
//   g++ -O3 -std=c++17 -o ispc_demo main.cpp sinx_interleaved.obj

#include <iostream>
#include <cmath>
#include "sinx_interleaved.h"

int main() {
    const int N = 8;
    const int terms = 5;

    float x[N] = {
        0.0f,
        0.5f,
        1.0f,
        1.5f,
        2.0f,
        2.5f,
        3.0f,
        3.14f
    };

    float result[N];

    ispc::ispc_sinx(N, terms, x, result);

    for (int i = 0; i < N; i++) {
        std::cout
            << "x = " << x[i]
            << "  ISPC = " << result[i]
            << "  std::sin = " << std::sin(x[i])
            << '\n';
    }

    return 0;
}